name: CI Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Dar permisos de ejecución a Maven Wrapper
      run: chmod +x mvnw

    - name: Compilar y Ejecutar Tests (Build & Test)
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: ./mvnw clean verify sonar:sonar -Dsonar.projectKey=soyminero02-a11y_Grupo-6-Jaime -Dsonar.organization=soyminero02-a11y -Dsonar.host.url=https://sonarcloud.io